#!/usr/bin/env python3

import os

def run(cmd): assert 0 == os.system(cmd)

def make_password():
    password = ""
    while len(password) < 6:
        x = chr(ord(os.urandom(1)))
        if x in "abcdefghkmnpqrstuvwxyz":
            password += x
    return password


n = 50

users = [ ("guest%d"%(i+1), make_password()) for i in range(n) ]

with open("/home/rstudio/guests.csv","w") as f:
    f.write("username,password\n")
    for name, password in users:
        f.write("%s,%s\n" % (name, password))

with open("/home/rstudio/guests.html","w") as f:
    print("<!DOCTYPE html>", file=f)
    for i, (name, password) in enumerate(users):
        print("<pre style=\"font-size: 110%; page-break-inside: avoid\">", file=f)
        #print("   Go to: "+ ..., file=f)
        print("Username: "+name, file=f)
        print("Password: "+password, file=f)
        print("", file=f)
        print("", file=f)
        print("</pre>", file=f)

for name, password in users:
    run("adduser --gecos '' --disabled-password "+name)
    run("echo "+name+":"+password+" |chpasswd")


